from kpidebug.data.connector import (
    ColumnType,
    TableColumn,
    TableDescriptor,
)

STRIPE_TABLES: list[TableDescriptor] = [
    TableDescriptor(
        key="charges",
        name="Charges",
        description="Payment charges processed through Stripe",
        columns=[
            TableColumn(
                key="id", name="ID",
                description="Charge identifier",
                type=ColumnType.STRING,
                is_primary_key=True,
            ),
            TableColumn(
                key="amount", name="Amount",
                description="Amount in minor units (cents)",
                type=ColumnType.NUMBER,
            ),
            TableColumn(
                key="currency", name="Currency",
                description="Three-letter currency code",
            ),
            TableColumn(
                key="status", name="Status",
                description="Charge status",
            ),
            TableColumn(
                key="description", name="Description",
                description="Charge description",
            ),
            TableColumn(
                key="customer", name="Customer",
                description="Customer ID",
            ),
            TableColumn(
                key="created", name="Created",
                description="Creation timestamp",
                type=ColumnType.DATETIME,
            ),
        ],
    ),
    TableDescriptor(
        key="customers",
        name="Customers",
        description="Stripe customers",
        columns=[
            TableColumn(
                key="id", name="ID",
                description="Customer identifier",
                type=ColumnType.STRING,
                is_primary_key=True,
            ),
            TableColumn(
                key="name", name="Name",
                description="Customer name",
            ),
            TableColumn(
                key="email", name="Email",
                description="Customer email",
            ),
            TableColumn(
                key="created", name="Created",
                description="Creation timestamp",
                type=ColumnType.DATETIME,
            ),
        ],
    ),
    TableDescriptor(
        key="subscriptions",
        name="Subscriptions",
        description="Recurring subscriptions",
        columns=[
            TableColumn(
                key="id", name="ID",
                description="Subscription identifier",
                type=ColumnType.STRING,
                is_primary_key=True,
            ),
            TableColumn(
                key="status", name="Status",
                description="Subscription status",
            ),
            TableColumn(
                key="amount", name="Amount",
                description="Plan amount in minor units",
                type=ColumnType.NUMBER,
            ),
            TableColumn(
                key="currency", name="Currency",
                description="Three-letter currency code",
            ),
            TableColumn(
                key="interval", name="Interval",
                description="Billing interval (month/year)",
            ),
            TableColumn(
                key="created", name="Created",
                description="Creation timestamp",
                type=ColumnType.DATETIME,
            ),
            TableColumn(
                key="current_period_start",
                name="Period Start",
                description="Current billing period start",
                type=ColumnType.DATETIME,
            ),
            TableColumn(
                key="current_period_end",
                name="Period End",
                description="Current billing period end",
                type=ColumnType.DATETIME,
            ),
        ],
    ),
    TableDescriptor(
        key="invoices",
        name="Invoices",
        description="Invoices generated by Stripe",
        columns=[
            TableColumn(
                key="id", name="ID",
                description="Invoice identifier",
                type=ColumnType.STRING,
                is_primary_key=True,
            ),
            TableColumn(
                key="amount_due", name="Amount Due",
                description="Amount due in minor units",
                type=ColumnType.NUMBER,
            ),
            TableColumn(
                key="amount_paid", name="Amount Paid",
                description="Amount paid in minor units",
                type=ColumnType.NUMBER,
            ),
            TableColumn(
                key="currency", name="Currency",
                description="Three-letter currency code",
            ),
            TableColumn(
                key="status", name="Status",
                description="Invoice status",
            ),
            TableColumn(
                key="customer", name="Customer",
                description="Customer ID",
            ),
            TableColumn(
                key="created", name="Created",
                description="Creation timestamp",
                type=ColumnType.DATETIME,
            ),
        ],
    ),
    TableDescriptor(
        key="refunds",
        name="Refunds",
        description="Refunds issued through Stripe",
        columns=[
            TableColumn(
                key="id", name="ID",
                description="Refund identifier",
                type=ColumnType.STRING,
                is_primary_key=True,
            ),
            TableColumn(
                key="amount", name="Amount",
                description="Refund amount in minor units",
                type=ColumnType.NUMBER,
            ),
            TableColumn(
                key="currency", name="Currency",
                description="Three-letter currency code",
            ),
            TableColumn(
                key="status", name="Status",
                description="Refund status",
            ),
            TableColumn(
                key="charge", name="Charge",
                description="Original charge ID",
            ),
            TableColumn(
                key="created", name="Created",
                description="Creation timestamp",
                type=ColumnType.DATETIME,
            ),
        ],
    ),
]

STRIPE_TABLES_BY_KEY: dict[str, TableDescriptor] = {
    t.key: t for t in STRIPE_TABLES
}
